---
title       : Random Normal Distribution
subtitle    : A 'Shiny' Application Produced in R 
author      : Jack Welch
job         : Developing Data Products, Data Science Specialization on Coursera
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Random Normal Distribution

Check out one of the coolest new apps recently published to the internet.  This new app is a training tool that allows a user to generate and to visualize their own random normal distribution.

1. Easy to Use
2. Dynamic Generation of Histogram
3. Select and visualize a change in 'n', the qty of numbers contained within the data set.
4. Select and visualize your own 'mu', or the the desired average of the distribution.
5. Select and visualize your own 'sd', or standard deviation of the distribution.

--- .kwd #id3 

## Histogram

```{r}
x<-rnorm(100000,mean=0, sd=1)
hist(x,breaks=150,xlim=c(-5,5),freq=FALSE)
```

More info ... [https://en.wikipedia.org/wiki/Normal_distribution](click here).


--- .kwd #id4 

## References

1. Caffo, Brian. (November 9, 2015). *Developing Data Products in R*. leanpub.com: Lean Publishing.

2. Sauer, Sebastian. (July 5, 2016). *How to add a logo to a slidify presentation*. GitHub.com. Retrieved from [https://sebastiansauer.github.io/slidify-logo/](https://sebastiansauer.github.io/slidify-logo/) on July 5, 2017.

3. Unauthored. *Normal distribution*. Wikipedia.com. Retrieved from [https://en.wikipedia.org/wiki/Normal_distribution](https://en.wikipedia.org/wiki/Normal_distribution) on July 5, 2017.



--- .kwd #id5 

## Contact Me

This new custom Shiny app and Slidify Presentation was prepared by:

### Jack Welch, Student


Developing Data Products

Data Science Specialization

Johns Hopkins University

Bloomberg School of Medicine

[https://www.coursera.org/learn/data-products/home/welcome](https://www.coursera.org/learn/data-products/home/welcome)

GitHub: [https://github.com/koolwebdezign](https://github.com/koolwebdezign)
